{% set name = "dash" %}
{% set version = "3.2.0" %}
{% set sha256 = "93300b9b99498f8b8ed267e61c455b4ee1282c7e4d4b518600eec87ce6ddea55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-remove-obsolete-components.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - flask >=1.0.4,<3.2
    - werkzeug <3.2
    - plotly >=5.0.0
    - importlib-metadata
    - typing_extensions >=4.1.1
    - requests
    - retrying
    - ansi2html
    - nest-asyncio
    # compress extra
    - flask-compress
    - setuptools
  run_constrained:
    # Obsolete components now included in dash.
    - dash-core-components ==2.0.0
    - dash-html-components ==2.0.0
    - dash-table ==5.0.0
    # diskcache extra
    - diskcache >=5.2.1
    - multiprocess >=0.70.12
    - psutil >=5.8.0
    # celery extra
    - redis >=3.5.3
    - celery >=5.1.2,<5.4.0
    - importlib-metadata <5  # [py<38]
    - redis-py >=3.5.3,<=5.0.4
    - kombu <5.4.0
    - black ==22.3.0
    - flake8 ==7.0.0
    - flaky ==3.8.1
    - flask-talisman ==1.0.0
    - ipython <9.0.0
    - mimesis <=11.1.0
    - mock ==4.0.3
    - numpy <=1.26.3
    - orjson ==3.10.3
    - pandas >=1.4.0
    - pylint ==3.0.3
    - pytest-sugar ==0.9.6
    - pyzmq ==25.1.2
    - xlrd >=2.0.1
    - jupyterlab <4.0.0

test:
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources
    - dash.dcc
    - dash.html
    - dash.dash_table
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://plotly.com/dash/
  doc_url: https://dash.plotly.com/
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps.
  description: |
    Built on top of Plotly.js, React and Flask, Dash ties modern UI elements like dropdowns,
    sliders, and graphs directly to your analytical Python code.



extra:
  recipe-maintainers:
    - moorepants
