{% set name = "dash" %}
{% set version = "4.4.1" %}
{% set ignore_tests = " --ignore=gh_src/tests/unit/test_browser.py" %}
{% set deselect_tests = " --deselect=gh_src/tests/unit/test_configs.py::test_missing_flask_compress_raises" %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh_src/tests/unit/test_app_runners.py::test_threaded_server_smoke"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh_src/tests/unit/test_app_runners.py::test_process_server_smoke"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh_src/tests/unit/pages/test_pages.py::test_path_to_module_name"' %}  # [win]
{% set deselect_tests = 'deselect_tests + " --deselect=gh_src/tests/unit/pages/test_pages.py::test_import_layouts_from_pages"' %}  # [win]
{% set deselect_tests = 'deselect_tests + " --deselect=gh_src/tests/unit/pages/test_pages_config.py::test_pages_folder_config"' %}  # [win]

# selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox
# Windows pathing is wrong
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9356ca7856bc496c12c5b6de5978aaf783e090d07450ee395ade1c0c2cbdf816
  - url: https://github.com/plotly/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7eca0a3111a15f1000aacf98f842f7608898a61baac153a7efa3f6a7b97b5c61
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - dash-generate-components = dash.development.component_generator:cli
    - dash-update-components = dash.development.update_components:cli
    - renderer = grayskull.__main__:main
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    # compress extra
    - flask-compress >=1.6.0
    - flask >=1.0.4,<3.2
    - werkzeug <3.2
    - plotly >=5.0.0
    - importlib-metadata
    - typing_extensions >=4.1.1
    - requests
    - retrying
    - nest-asyncio
  run_constrained:
    # Obsolete components now included in dash. In components folder.
    - dash-core-components >=4.0.0
    - dash-html-components >=4.0.0
    - dash-table ==7.0.0
    # diskcache extra
    - diskcache >=5.2.1
    - multiprocess >=0.70.12
    - psutil >=5.8.0
    # celery extra
    - redis >=3.5.3
    - celery >=5.1.2,<5.4.0
    - importlib-metadata <5  # [py<38]
    - redis-py >=3.5.3,<=5.0.4
    - kombu <5.4.0
    # ci extra
    - black ==22.3.0
    - flake8 ==7.0.0
    - flaky ==3.8.1
    - flask-talisman ==1.0.0
    - ipython <9.0.0
    - mimesis <=11.1.0
    - mock ==4.0.3
    - numpy <=1.26.3
    - orjson >=3.10.3
    - pandas >=1.4.0
    - pylint ==3.0.3
    - pyzmq>=26.0.0
    - pytest-sugar ==1.1.1
    - xlrd >=2.0.1
    - jupyterlab <4.0.0
    - mypy ==1.15.0

test:
  source_files:
    - gh_src/tests/unit
    - gh_src/tests/conftest.py
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources
    - dash.dcc
    - dash.html
    - dash.dash_table
  requires:
    - pip
    - pytest
    - pytest-mock
    - coloredlogs
    - grayskull
    - percy
    - mock
    - yaml
  commands:
    - pip check
    - dash-generate-components --help
    - dash-update-components --help
    - renderer --help
    - pytest -v gh_src/tests {{ ignore_tests }} {{ deselect_tests }}

about:
  home: https://plotly.com/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps.
  description: |
    Built on top of Plotly.js, React and Flask, Dash ties modern UI elements like dropdowns,
    sliders, and graphs directly to your analytical Python code.
  doc_url: https://dash.plotly.com
  dev_url: https://github.com/plotly/dash

extra:
  recipe-maintainers:
    - moorepants
