{% set name = "dash" %}
{% set version = "0.26.0" %}
{% set sha256 = "1f34cb425ef1ee0ab93090345891cba7acb4651725ea80110e7e2a8d636cd823" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - flask >=0.12
    - flask-compress
    - plotly
    - dash-renderer

test:
  imports:
    - dash.authentication
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python framework for building reactive web-apps.'

extra:
  recipe-maintainers:
    - moorepants
