travis:
  secure:
    BINSTAR_TOKEN: Z8CKEyOE2Tni+xo0gPRhX2VEjmUNh6Mj6Cas4opiDcXRFlzDyD1wku1QVetDi1IoVW9DrqnAXP6G6v0llnTjJRUpdz1W7qBJsU2R7mVs9AC3ecuoW8ImJ2fsKyHq6JzzIJGSnI2Tf7QyHUlpCEYbau+MCiCjf23dH08GpTgVGGJ2EpBzdXERfsnK1+HxL+2ct4knEFfitHfIQREqJ7hFUwnrIEo29zAcGCXj5+EhioelxOQPm/+Mq4AvPyvoHkuULUtA+2SIUBLRZO/8nkQo7VFXoS0BapeHFfJG362V786FgOSaazb6ZFuzXrcIr0I4whnB4Ku435ScLzmjN6R188A1mP9gLYf3qGB+ML3mrQqr4d4qMwRQ6iZcE1zgRnfDIPHINuvhPPkCpzgMt4YVEm3GpkuzF/VjxG4lG8XVsMNjdyDxa3yWYTb9OhEj7xdXhv+bRLf9LHM8gBw1p8Qh/FSmEMuputwU4vwjOYIxbf2xta0lgfezcoWCyU3PeZddfraLvpc9c3wjye4y+ZIXhUy0d98lVNmb7rrNUXzfgoeHZK5uvg2zL9xcD85l93bwaK2JhnnYStxCSPcsKr4Fg6lVQftWNhz3B+BTq4cGK4QO6YkACm1exvv3dITWnYwPtTBnJ0QTkWSuzOWLPMWBuR0vBNg0VCBUHAlfm8ngTtM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
