travis:
  secure:
    BINSTAR_TOKEN: sPy05AK6dXeDN+jmEw+cClqLZFd5kmjjO2j3cupF95ZH87a+RZNrOJ9+179tqRixl7IYidNbGQNEO5hpeDlV292YP8P9V9f7c3VtAYVIh/PaHhsSDPcV0TESU/q1K6gTumK0gLsloLoDuFlvJm64Dhcwbzp8HRgzTf9m1HOFU8WPVneI/MZRor9noT+RQmvxkiGhUTL7ZFDp9smw/WQEK4VaGV/iSwCMs6o76Qi+qbFFtajsABWaEkZU+S6n3tKLrsexfS0c6xeliv8NaIY7d6ABklVl1jaAu/Q3gjp6z7e04TvI8g7jLcwYV/Z54LtTEi3u8oJNGamlbYpjanf+XXUYG0CWgqIrImd4Kw5CnNXfeRDfPcmv3Y8/hMhNsWpYRLdrOmYMZ4gzGwOmmH5Yk2Sznk57FbsAO70DGaYwc2TMNi588oPCT8fD/Kq9JLUAUVjXew0mES0NH0pfnZ6p69ovo2UHQnNKzHSzpReJMkk7cgKGEMI23LPqsi5kvJVtJyNIDGp9Z8F662qx4ZeLqXpfTU3Ek1usTxXiJa6hK1VvoyuhxDd40kU3XPJP1i/kfCji9TDCoHUOYcmJFGP+HlokjmXs7In8V81SU769jDn4GkFgGENISy2VrqpJupzfcoYFQuMFSU6c3+vrT+6MI+mApO4KwJKnIcyhqZElDmA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
